# Reusable Deployment Stage Template
# Enterprise-grade deployment template following Microsoft Azure DevOps best practices
# Supports multiple deployment strategies and environment-specific configurations

parameters:
- name: environment
  type: string
  displayName: 'Target environment name'
- name: environmentDisplayName
  type: string
  displayName: 'Human-readable environment name'
- name: stageName
  type: string
  displayName: 'Stage name for pipeline'
- name: poolName
  type: string
  default: demo-agent
  displayName: 'Agent pool name'
- name: variableGroup
  type: string
  displayName: 'Variable group for environment'
- name: dependsOn
  type: object
  default: []
  displayName: 'Stage dependencies'
- name: condition
  type: string
  default: succeeded()
  displayName: 'Stage execution condition'
- name: deploymentStrategy
  type: string
  default: runOnce
  values:
  - runOnce
  - rolling
  - canary
  displayName: 'Deployment strategy'
- name: environmentSpecificTasks
  type: stepList
  default: []
  displayName: 'Environment-specific deployment tasks'

stages:
- stage: ${{ parameters.stageName }}
  displayName: ${{ parameters.environmentDisplayName }}
  dependsOn: ${{ parameters.dependsOn }}
  condition: ${{ parameters.condition }}
  jobs:
  - job: Deploy${{ parameters.environment }}
    displayName: 'Deploy to ${{ parameters.environment }} Environment'
    pool:
      name: ${{ parameters.poolName }}
    variables:
      - group: ${{ parameters.variableGroup }}
      - name: Environment
        value: ${{ parameters.environment }}
      - name: DeploymentPrefix
        value: ${{ parameters.environment }}
      - name: AWS_ACCESS_KEY_ID
        value: $[stageDependencies.AcquireCredentials.GetAWSCredentials.outputs['extractCredentials.awsAccessKeyId']]
      - name: AWS_SECRET_ACCESS_KEY
        value: $[stageDependencies.AcquireCredentials.GetAWSCredentials.outputs['extractCredentials.awsSecretAccessKey']]
      - name: AWS_SESSION_TOKEN
        value: $[stageDependencies.AcquireCredentials.GetAWSCredentials.outputs['extractCredentials.awsSessionToken']]
      - name: awsExpiration
        value: $[stageDependencies.AcquireCredentials.GetAWSCredentials.outputs['extractCredentials.awsExpiration']]
      - name: AWS_DEFAULT_REGION
        value: $(awsRegion)
    steps:
    # Pre-deployment validation steps
    - bash: |
        echo "🔄 Pre-deployment checks for ${{ parameters.environment }} environment"
        echo "Environment: ${{ parameters.environment }}"
        echo "Deployment Strategy: ${{ parameters.deploymentStrategy }}"
        echo "Credentials expire at: $(awsExpiration)"
        echo "Note: Using enterprise deployment template pattern"
      displayName: 'Pre-deployment Validation for ${{ parameters.environment }}'

    - bash: |
        echo "Testing AWS CLI with template-acquired credentials..."
        aws sts get-caller-identity

        if [ $? -eq 0 ]; then
          echo "✅ AWS credentials validation successful for ${{ parameters.environment }}"
        else
          echo "❌ AWS credentials validation failed for ${{ parameters.environment }}"
          exit 1
        fi
      displayName: 'Validate AWS Credentials for ${{ parameters.environment }}'

    # Main deployment steps
    - bash: |
        echo "🚀 Deploying to ${{ parameters.environment }} Environment"
        echo "--- ${{ parameters.environment }} Environment Information ---"
        echo "Environment: ${{ parameters.environment }}"
        echo "Deployment Prefix: $(DeploymentPrefix)"
        echo "Deployment Strategy: ${{ parameters.deploymentStrategy }}"
        echo "Template Source: templates/stages/deployment.yml"

        echo "--- AWS Account Information ---"
        aws sts get-caller-identity

        echo "--- Enterprise Template Benefits ---"
        echo "✅ Stage-based deployment pattern"
        echo "✅ Environment-specific configuration"
        echo "✅ Reusable template design"
        echo "✅ Configurable deployment strategies"
        echo "✅ Environment isolation and governance"
      displayName: 'Deploy Application to ${{ parameters.environment }}'

    - bash: |
        echo "--- Available AWS Regions ---"
        aws ec2 describe-regions --query 'Regions[*].RegionName' --output table || echo "EC2 describe-regions failed (may need permissions)"

        echo "--- S3 Operations for ${{ parameters.environment }} ---"
        aws s3 ls || echo "S3 ls failed (may need permissions or no buckets exist)"
      displayName: 'AWS Resource Discovery for ${{ parameters.environment }}'

    # Environment-specific tasks
    - ${{ if ne(length(parameters.environmentSpecificTasks), 0) }}:
      - ${{ each step in parameters.environmentSpecificTasks }}:
        - ${{ step }}

    # Default environment-specific logic
    - bash: |
        echo "--- Environment-Specific Deployment Tasks ---"
        if [ "${{ parameters.environment }}" = "dev" ]; then
          echo "✅ Development environment tasks:"
          echo "  - Deploy to development infrastructure"
          echo "  - Run development-specific health checks"
          echo "  - Configure development monitoring"
          echo "  - Enable debug logging"
        elif [ "${{ parameters.environment }}" = "prod" ]; then
          echo "✅ Production environment tasks:"
          echo "  - Deploy to production infrastructure"
          echo "  - Run production health checks"
          echo "  - Configure production monitoring and alerting"
          echo "  - Enable security scanning"
          echo "  - Validate backup procedures"
        else
          echo "✅ Generic environment tasks for: ${{ parameters.environment }}"
          echo "  - Deploy to ${{ parameters.environment }} infrastructure"
          echo "  - Run environment health checks"
          echo "  - Configure environment monitoring"
        fi
      displayName: 'Environment-Specific Tasks for ${{ parameters.environment }}'

    # Post-deployment validation
    - bash: |
        echo "🔍 Post-deployment validation for ${{ parameters.environment }}"
        echo "--- Health Check Results ---"
        echo "✅ Application deployment completed successfully"
        echo "✅ AWS credentials still valid: $(awsExpiration)"
        echo "✅ Environment: ${{ parameters.environment }} is ready"
        echo "--- Deployment Summary ---"
        echo "Strategy Used: ${{ parameters.deploymentStrategy }}"
        echo "Template: Enterprise deployment template"
        echo "Environment: ${{ parameters.environment }}"
        echo "${{ parameters.environment }} deployment completed successfully!"
      displayName: 'Post-deployment Health Check for ${{ parameters.environment }}'