FROM arm64v8/alpine
ENV TARGETARCH="linux-musl-arm64"

RUN apk update && \
  apk upgrade && \
  apk add bash curl gcc git icu-libs jq musl-dev python3-dev libffi-dev openssl-dev cargo make py3-pip zip unzip

# Install Azure CLI
RUN pip install --break-system-packages azure-cli

WORKDIR /azp/

COPY ./start.sh ./
RUN chmod +x ./start.sh

# Create shared storage directory for EFS volume before switching to non-root user
# This directory will be mounted to an EFS file system in ECS Fargate
RUN mkdir -p /shared-storage

# Create non-root user and set ownership
# NOTE: Alpine's adduser -D creates user with UID:GID = 1000:1000 by default
# This UID/GID must match the EFS Access Point POSIX user configuration
RUN adduser -D agent
RUN chown agent ./
RUN chown agent /shared-storage

# Switch to non-root user for running the agent
# IMPORTANT: When using EFS without an access point, this user may not have
# permission to create subdirectories in /shared-storage even with ownership.
# This is because EFS enforces POSIX permissions at the filesystem level.
#
# SOLUTION: Use an EFS Access Point with matching UID/GID (1000:1000)
# See: https://stackoverflow.com/questions/65965998/efs-mount-on-ecs-fargate-read-write-permissions-denied-for-non-root-user
# See: https://medium.com/@viniciuscolutti/how-to-use-efs-volumes-with-non-root-user-on-ecs-fargate-containers-b927e5db46c9
USER agent

ENTRYPOINT [ "./start.sh" ]
