# Test Pipeline 8 - Template Nesting Demo
# Demonstrates Azure DevOps template nesting using a reusable AcquireCredentials stage
# Based on Microsoft best practices for template organization and reusability

trigger: none  # Manual trigger only for demo purposes

pool:
  name: demo-agent  # Change this to match your agent pool name

variables:
  - group: dev

# Include the reusable AcquireCredentials stage template
stages:
- template: templates/stages/acquire-credentials.yml
  parameters:
    poolName: demo-agent
    variableGroup: dev
    stageName: AcquireCredentials
    displayName: 'Stage 1: Acquire AWS Temporary Credentials (Template)'

# Development Environment Deployment
- template: templates/stages/deployment.yml
  parameters:
    environment: dev
    environmentDisplayName: 'Stage 2a: Development Deployment (Enterprise Template)'
    stageName: DevDeployment
    poolName: demo-agent
    variableGroup: dev
    dependsOn: AcquireCredentials
    condition: succeeded()
    deploymentStrategy: runOnce
    environmentSpecificTasks:
    - bash: |
        echo "🔧 Development-specific deployment tasks"
        echo "Enabling debug mode and verbose logging"
        echo "Setting up development monitoring dashboards"
      displayName: 'Development Environment Setup'

# Production Environment Deployment
- template: templates/stages/deployment.yml
  parameters:
    environment: prod
    environmentDisplayName: 'Stage 2b: Production Deployment (Enterprise Template)'
    stageName: ProdDeployment
    poolName: demo-agent
    variableGroup: dev  # TODO: Create separate prod variable group for production
    dependsOn:
      - AcquireCredentials
      - DevDeployment
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    deploymentStrategy: runOnce
    environmentSpecificTasks:
    - bash: |
        echo "🛡️ Production-specific deployment tasks"
        echo "Running security scans and compliance checks"
        echo "Setting up production monitoring and alerting"
        echo "Configuring backup and disaster recovery"
      displayName: 'Production Environment Setup'