# Test Pipeline 3 for AWS Roles Anywhere Credential Sharing
# Demonstrates separating credential acquisition from usage across jobs
# Based on AWS IAM Roles Anywhere with credential helper

trigger: none  # Manual trigger only for demo purposes

pool:
  name: demo-agent  # Change this to match your agent pool name

variables:
  - group: dev

stages:
- stage: AWSCredentialDemo
  displayName: 'AWS Credential Acquisition and Usage Demo'
  jobs:
  - job: GetAWSCredentials
    displayName: 'Job 1: Acquire AWS Temporary Credentials'
    steps:
    - bash: wget https://rolesanywhere.amazonaws.com/releases/1.7.1/Aarch64/Linux/Amzn2023/aws_signing_helper; chmod +x aws_signing_helper; # https://docs.aws.amazon.com/rolesanywhere/latest/userguide/credential-helper.html
      displayName: Install AWS Signer

    - task: DownloadSecureFile@1
      name: Certificate
      displayName: 'Download certificate'
      inputs:
        secureFile: 'certificate.crt'

    - task: DownloadSecureFile@1
      name: Privatekey
      displayName: 'Download private key'
      inputs:
        secureFile: 'private.key'

    - bash: |
        set -e
        echo "Setting up AWS credential process..."
        aws configure set credential_process "./aws_signing_helper credential-process --certificate $(Certificate.secureFilePath) --private-key $(Privatekey.secureFilePath) --trust-anchor-arn $(TRUSTANCHORARN) --profile-arn $(PROFILEARN) --role-arn $(ROLEARN)" --profile default
        
        echo "Enabling AWS SDK config loading..."
        export AWS_SDK_LOAD_CONFIG=1
        
        echo "Testing credential acquisition..."
        aws sts get-caller-identity
        
        echo "Extracting temporary credentials..."
        # Get the raw credentials from the credential helper
        CREDS_JSON=$(./aws_signing_helper credential-process --certificate $(Certificate.secureFilePath) --private-key $(Privatekey.secureFilePath) --trust-anchor-arn $(TRUSTANCHORARN) --profile-arn $(PROFILEARN) --role-arn $(ROLEARN))
        
        # Parse and extract individual credential components
        AWS_ACCESS_KEY_ID=$(echo $CREDS_JSON | jq -r '.AccessKeyId')
        AWS_SECRET_ACCESS_KEY=$(echo $CREDS_JSON | jq -r '.SecretAccessKey')
        AWS_SESSION_TOKEN=$(echo $CREDS_JSON | jq -r '.SessionToken')
        EXPIRATION=$(echo $CREDS_JSON | jq -r '.Expiration')
        
        # Validate credentials were extracted
        if [ "$AWS_ACCESS_KEY_ID" = "null" ] || [ -z "$AWS_ACCESS_KEY_ID" ]; then
          echo "ERROR: Failed to extract AWS_ACCESS_KEY_ID"
          exit 1
        fi
        
        if [ "$AWS_SECRET_ACCESS_KEY" = "null" ] || [ -z "$AWS_SECRET_ACCESS_KEY" ]; then
          echo "ERROR: Failed to extract AWS_SECRET_ACCESS_KEY" 
          exit 1
        fi
        
        if [ "$AWS_SESSION_TOKEN" = "null" ] || [ -z "$AWS_SESSION_TOKEN" ]; then
          echo "ERROR: Failed to extract AWS_SESSION_TOKEN"
          exit 1
        fi
        
        echo "Successfully extracted temporary credentials"
        echo "Credentials expire at: $EXPIRATION"
        
        # Make credentials available to next job using output variables
        echo "##vso[task.setvariable variable=awsAccessKeyId;isOutput=true]$AWS_ACCESS_KEY_ID"
        echo "##vso[task.setvariable variable=awsSecretAccessKey;isOutput=true]$AWS_SECRET_ACCESS_KEY" 
        echo "##vso[task.setvariable variable=awsSessionToken;isOutput=true]$AWS_SESSION_TOKEN"
        echo "##vso[task.setvariable variable=awsExpiration;isOutput=true]$EXPIRATION"
        echo "##vso[task.setvariable variable=credentialsReady;isOutput=true]true"
      name: extractCredentials
      displayName: 'Extract and Share AWS Temporary Credentials'
      
  - job: UseAWSCredentials
    displayName: 'Job 2: Use AWS Temporary Credentials'
    dependsOn: GetAWSCredentials
    condition: and(succeeded(), eq(dependencies.GetAWSCredentials.outputs['extractCredentials.credentialsReady'], 'true'))
    variables:
      AWS_ACCESS_KEY_ID: $[ dependencies.GetAWSCredentials.outputs['extractCredentials.awsAccessKeyId'] ]
      AWS_SECRET_ACCESS_KEY: $[ dependencies.GetAWSCredentials.outputs['extractCredentials.awsSecretAccessKey'] ]
      AWS_SESSION_TOKEN: $[ dependencies.GetAWSCredentials.outputs['extractCredentials.awsSessionToken'] ]
      awsExpiration: $[ dependencies.GetAWSCredentials.outputs['extractCredentials.awsExpiration'] ]
      AWS_DEFAULT_REGION: $(awsRegion)
    steps:
    - bash: |
        echo "Setting up AWS environment variables from Job 1..."
        
        echo "Credentials expire at: $(awsExpiration)"
        
        # Validate credentials work
        echo "Testing AWS CLI with temporary credentials..."
        aws sts get-caller-identity
        
        if [ $? -eq 0 ]; then
          echo "AWS credentials are working correctly!"
        else
          echo "AWS credentials failed to work"
          exit 1
        fi
      displayName: 'Validate AWS Credentials from Job 1'
      
    - bash: |
     
        echo "Performing AWS operations with temporary credentials..."
        
        # Example AWS operations - customize based on your needs
        echo "--- AWS Account Information ---"
        aws sts get-caller-identity
        
        echo "--- Available AWS Regions ---"
        aws ec2 describe-regions --query 'Regions[*].RegionName' --output table || echo "EC2 describe-regions failed (may need permissions)"
        
        echo "--- S3 Buckets (if accessible) ---" 
        aws s3 ls || echo "S3 ls failed (may need permissions or no buckets exist)"
      displayName: 'Perform AWS Operations with Shared Credentials'